name: hamromart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  image_picker: ^1.1.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.2
  velocity_x: ^4.2.1
  pinput: ^5.0.0
  firebase_app_check: ^0.2.2+7
  fluttertoast: ^8.0.9
  country_picker: ^2.0.25
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_riverpod: ^2.5.1
  flutter_rating_bar: ^4.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/ic_launcher_shop.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/
    - assets/icons/
    - assets/General/
    - assets/all/
    - assets/babycare/
    - assets/beverages/
    - assets/chocolates/
    - assets/food/
    - assets/fruits/
    - assets/snacks/
    - assets/vegetables/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300



