// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDaA-sBSYStbGlahEtoVhhQVrplTcgLbYk',
//     appId: '1:981994564753:web:96c1423256122466dfe330',
//     messagingSenderId: '981994564753',
//     projectId: 'onlineshoppings-26f37',
//     authDomain: 'onlineshoppings-26f37.firebaseapp.com',
//     storageBucket: 'onlineshoppings-26f37.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBywMJEh_J7rl6V7CP0qoIbFgYKqYIpZZs',
//     appId: '1:981994564753:android:d3757457e80b6a6adfe330',
//     messagingSenderId: '981994564753',
//     projectId: 'onlineshoppings-26f37',
//     storageBucket: 'onlineshoppings-26f37.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD7Igto47Q0xtuNTLIJOVSI1utg2ApHvVE',
//     appId: '1:981994564753:ios:c6b681d21d683dfadfe330',
//     messagingSenderId: '981994564753',
//     projectId: 'onlineshoppings-26f37',
//     storageBucket: 'onlineshoppings-26f37.appspot.com',
//     androidClientId: '981994564753-kpblilsahk2be4cto55iihad30voucqg.apps.googleusercontent.com',
//     iosClientId: '981994564753-t4mbeqf9i09hnafok319gpqnllbnq91v.apps.googleusercontent.com',
//     iosBundleId: 'com.example.onlineshoppings',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDaA-sBSYStbGlahEtoVhhQVrplTcgLbYk',
//     appId: '1:981994564753:web:d16add721b771776dfe330',
//     messagingSenderId: '981994564753',
//     projectId: 'onlineshoppings-26f37',
//     authDomain: 'onlineshoppings-26f37.firebaseapp.com',
//     storageBucket: 'onlineshoppings-26f37.appspot.com',
//   );
// }
